name: Deploy Web Aplication Conciliacion

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get Github action IP
      id: ip
      uses: haythem/public-ip@v1.2
        
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/16  
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.'GP01-BACKEND'.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.'GP01-BACKEND'.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        
    - name: Pull Changes From Repo to prod Front Web Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/GP01-FRONT
          git stash
          git pull origin main
    
    - name: Install dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: Deploy on Server Front EC2
      run: |
        [ -d /ruta/al/directorio ] && \
        echo "El directorio CoffeeConnectFront existe" && \
        sudo cp -r dist/* /usr/share/nginx/html/ && \
        sudo service nginx restart \
        || echo "El directorio CoffeeConnectFront no existe" &&\
        echo "Revisar step anterior"

    - name: Clean up
      run: |
        rm -rf dist/*

    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/16
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      if: always()
